#!/bin/bash

me=`basename $0`
version="0.2"

print_help(){
    echo "$me
version: $version 
the eazy way to connect to your 3G/LTE broadband provider

Help:
before first use change the variables in the script for your needs
PIN="XYZA"
APN="ABC.PROVIDER.COM"
Make sure that this these ones are correct, in case of malfunctions

Also notice that wvdial and usb_modeswitch is needed.

For further instructions, get help on https://github.com/groldo/freegdial"
}

case "$1" in
    *)                  print_help;;
esac

# Enter your Pin and APN
PIN=""
APN="" # e.g. internet.t-d1.de

# If your broadband service provider gave you credentials you can enter them here.
# Otherwise just leave the defaults
USER="any"
PASS="any"

CONF="/tmp/freegdial.conf"

# check $PIN
if [[ ! -z "$PIN" ]]; then
    echo "PIN set"
else 
    echo "PIN is not set!"
    exit 1
fi

# check $APN
if [[ ! -z "$APN" ]]; then
    echo "APN set"
else 
    echo "APN is not set!"
    exit 1
fi

# check if required software is installed
type wvdial >/dev/null 2>&1 || { echo >&2 "Error: wvdial is required."; exit 1; }
type usb_modeswitch >/dev/null 2>&1 || { echo >&2 "Error: usb_modeswitch is required."; exit 1; }

# check for root privilege
if [ "$(id -u)" != "0" ]; then
	echo "Sudo that!"
	exit 1
fi

# if wvdial is already running nothing happens
if ! pidof wvdial &> /dev/null; then

	now=$(date +"%H:%M %m/%d/%Y")

	# create log file and/or set
	if [ -f /var/log/freegdial.log ]; then
		LOG=/var/log/freegdial.log
	else
		touch /var/log/freegdial.log
		LOG=/var/log/freegdial.log
	fi
	
	# set config file
	cat >> $CONF << FREEGDIAL_CONF
[Dialer Defaults]
Init1 = ATZ
Init2 = ATQ0 V1 E1 S0=0
Modem Type = Analog Modem
ISDN = 0
Modem = /dev/ttyUSB0
Baud = 115200

[Dialer pin]
Init3 = AT+CPIN=$PIN
[Dialer pinstatus]
Init4 = AT+CPIN?
[Dialer umts]
Carrier Check = no
Init5 = AT+CGDCONT=1,"IP","$APN"
Stupid Mode = 1
Phone = *99#
Username = $USER
Password = $PASS
Dial Attemtps = 2
FREEGDIAL_CONF
	
	### switch mode of usb modem
	if lsusb | grep 12d1 &> /dev/null;then
		usb_modeswitch -v 12d1 -p 14fe -M '55534243123456780000000000000011062000000100000000000000000000' &> /dev/null
		sleep 1
	else
		echo $now 'Modeswitch failed' >> $LOG
		exit 0
	fi

	### connect to mobile broadband
	if lsusb | grep Modem &> /dev/null;then
		wvdial -C $CONF pin &> /dev/null
		sleep 1
		wvdial -C $CONF umts &> /dev/null &
		echo $now 'Connection established' >> $LOG
	else
		echo $now 'No modem device connected' >> $LOG
		exit 0
	fi
else
	echo $now 'wvdial already started'
	exit 0
fi
